apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votes-api-ingress
  namespace: votes-app
spec:
  defaultBackend:
    service:
      name: votes-api
      port:
        number: 3333
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: votes-app
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: upvote-app
                port:
                  number: 3001